#!/bin/bash

echo "âž?Ignore Permission Changes"
git config core.fileMode false

echo "âž?Set Correct Permissions"
chmod -R 777 storage

echo "âž?Install Composer Dependencies"
[[ -d vendor ]] || composer install

echo "âž?Install NPM Dependencies"
[[ -d node_modules ]] || npm install

echo "âž?Build Project Assets"
[[ -d assets/vendor ]] || npx gulp compile

echo "âž?Listen To Incoming Requests"
php-fpm
